[general]
live_config_reload = true
working_directory = "./"

[terminal]
shell = "pwsh"

[window]
dynamic_padding = true
decorations = "Transparent"
decorations_theme_variant = "Dark"
opacity = 0.8
dynamic_title = true

[font]
normal= { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

